"""slack_messages

Revision ID: 7c70cff89626
Revises: 97dd03d6ec76
Create Date: 2016-08-03 15:54:13.871790

"""

# revision identifiers, used by Alembic.
revision = '7c70cff89626'
down_revision = '97dd03d6ec76'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'slack_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('alert_id', sa.Integer(), nullable=False),
        sa.Column('channel', sa.String(), nullable=False),
        sa.Column('timestamp', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_messages')
    ### end Alembic commands ###
